apiVersion: v1
kind: Secret
metadata:
  name: {{ include "model-catalog.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "model-catalog.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_USER: {{ .Values.secrets.databaseUser | quote }}
  DATABASE_PASSWORD: {{ .Values.secrets.databasePassword | quote }}
  DATABASE_URL: "postgresql://{{ .Values.secrets.databaseUser }}:{{ .Values.secrets.databasePassword }}@{{ .Values.config.databaseHost }}:{{ .Values.config.databasePort }}/{{ .Values.config.databaseName }}"
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}

