apiVersion: v1
kind: ConfigMap
metadata:
  name: spot-termination-handler
  namespace: gpu-workloads
data:
  handler.sh: |
    #!/bin/bash
    # Spot Instance Termination Handler
    # Monitors for EC2 spot termination notices and handles graceful shutdown
    
    echo "Starting spot termination handler..."
    
    while true; do
      # Check for AWS spot termination notice (2 minute warning)
      HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://169.254.169.254/latest/meta-data/spot/termination-time)
      
      if [ "$HTTP_CODE" == "200" ]; then
        echo "⚠️  SPOT TERMINATION NOTICE RECEIVED!"
        
        # Get termination time
        TERMINATION_TIME=$(curl -s http://169.254.169.254/latest/meta-data/spot/termination-time)
        echo "Termination scheduled at: $TERMINATION_TIME"
        
        # Trigger checkpoint for all running workflows
        echo "Triggering checkpoint for running workflows..."
        kubectl get workflows -n gpu-workloads -l state=Running -o name | \
          xargs -I {} kubectl patch {} --type=merge -p '{"spec":{"suspend":true}}'
        
        # Save checkpoint metadata
        echo "Saving checkpoint metadata..."
        kubectl annotate node $NODE_NAME checkpoint-timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        
        # Drain the node
        echo "Draining node $NODE_NAME..."
        kubectl drain $NODE_NAME --ignore-daemonsets --delete-emptydir-data --force
        
        echo "✅ Graceful shutdown complete. Ready for termination."
        break
      fi
      
      # Check every 5 seconds
      sleep 5
    done
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spot-termination-handler
  namespace: gpu-workloads
  labels:
    app: spot-termination-handler
spec:
  selector:
    matchLabels:
      app: spot-termination-handler
  template:
    metadata:
      labels:
        app: spot-termination-handler
    spec:
      hostNetwork: true
      serviceAccountName: spot-handler
      
      # Only run on spot instance nodes
      nodeSelector:
        node.kubernetes.io/instance-lifecycle: spot
      
      tolerations:
      - key: "spot-instance"
        operator: "Exists"
        effect: "NoSchedule"
      
      containers:
      - name: handler
        image: bitnami/kubectl:latest
        command: ["/bin/bash"]
        args: ["/scripts/handler.sh"]
        
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        
        volumeMounts:
        - name: handler-script
          mountPath: /scripts
        
        securityContext:
          privileged: true
      
      volumes:
      - name: handler-script
        configMap:
          name: spot-termination-handler
          defaultMode: 0755
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spot-handler
  namespace: gpu-workloads
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spot-handler-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows"]
  verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spot-handler-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spot-handler-role
subjects:
- kind: ServiceAccount
  name: spot-handler
  namespace: gpu-workloads

