apiVersion: v1
kind: ConfigMap
metadata:
  name: model-catalog-config
  namespace: model-catalog
  labels:
    app: model-catalog-api
data:
  # Application settings
  APP_NAME: "Model Catalog Backend"
  VERSION: "0.1.0"
  DEBUG: "false"
  API_V1_STR: "/api/v1"
  
  # Database settings (non-sensitive)
  DATABASE_HOST: "postgresql.data-storage.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "model_catalog"
  
  # Redis settings
  REDIS_HOST: "redis.model-catalog.svc.cluster.local"
  REDIS_PORT: "6379"
  
  # CORS settings
  CORS_ORIGINS: '["http://localhost:3000","http://localhost:8080","https://api.example.com"]'
  
  # Performance settings
  WORKERS: "4"
  MAX_CONNECTIONS: "100"
  POOL_SIZE: "20"
  
  # Logging
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"

