apiVersion: v1
kind: Service
metadata:
  name: model-catalog-api
  namespace: model-catalog
  labels:
    app: model-catalog-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: ClusterIP
  selector:
    app: model-catalog-api
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  sessionAffinity: None
---
# Headless service for StatefulSet if needed
apiVersion: v1
kind: Service
metadata:
  name: model-catalog-api-headless
  namespace: model-catalog
  labels:
    app: model-catalog-api
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: model-catalog-api
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP

