apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-catalog-backend
  namespace: model-catalog
  labels:
    app: model-catalog-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: model-catalog-backend
  template:
    metadata:
      labels:
        app: model-catalog-backend
    spec:
      containers:
      - name: model-catalog-backend
        image: model-catalog-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: model-catalog-secret
              key: DATABASE_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: model-catalog-secret
              key: SECRET_KEY
        envFrom:
        - configMapRef:
            name: model-catalog-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
